### PR TITLE
use external API from acs-engine

### PR DESCRIPTION
**Pull request by jim-minter**
@pweil- @kargakis @mjudeikis fyi

Based on #59 
Removes api.Manifest and replaces it with acs-engine internal and external api.  This is currently at https://github.com/jim-minter/acs-engine/commit/osaapi
Ugly but it works.

### CODE REVIEW

**Comment by mjudeikis** [comment]
tested, lgtm

**Comment by jim-minter** [comment]
@pweil- this works even though it's not that pretty.  @mjudeikis has got a PR that builds on it.  Up to you but I'd be inclined to hit merge and deal with any fallout ;)

**Comment by mjudeikis** [comment]
https://github.com/jim-minter/azure-helm/issues/63 might be my env problems, but would be nice if anybody else could try

**Comment by pweil-** [comment]
Closing for #66

**Pull request merged**
